"""
Dedup foto della galleria: usa un perceptual hash semplice (average hash 8x8
grayscale) per raggruppare le foto visivamente simili e mantenerne UNA per
gruppo. Riscrive js/foto-manifest.js.

Lanciare quando vengono aggiunte foto nuove o per ripulire.
"""
import os
import re
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
FOLDER = ROOT / "assets" / "img" / "bazzana"
MANIFEST = ROOT / "js" / "foto-manifest.js"
THRESHOLD = 7  # hamming distance massima per considerare due foto "uguali"


def avg_hash(path, size=8):
    img = Image.open(path).convert("L").resize((size, size), Image.BILINEAR)
    pixels = list(img.getdata())
    avg = sum(pixels) / len(pixels)
    return "".join("1" if p >= avg else "0" for p in pixels)


def hamming(a, b):
    return sum(c1 != c2 for c1, c2 in zip(a, b))


def main():
    files = sorted(f for f in os.listdir(FOLDER)
                   if f.lower().startswith("foto-") and f.lower().endswith(".jpg"))
    hashes = []
    for f in files:
        try:
            hashes.append((f, avg_hash(FOLDER / f)))
        except Exception as e:
            print(f"err {f}: {e}")

    keep = []
    used = set()
    removed_count = 0
    for i, (fname, h) in enumerate(hashes):
        if fname in used:
            continue
        keep.append(fname)
        used.add(fname)
        # Marca come "usate" tutte le foto visivamente simili
        for j in range(i + 1, len(hashes)):
            other_fname, other_h = hashes[j]
            if other_fname in used:
                continue
            if hamming(h, other_h) <= THRESHOLD:
                used.add(other_fname)
                removed_count += 1

    print(f"Totale: {len(files)} foto")
    print(f"Mantenute: {len(keep)}")
    print(f"Rimosse (duplicati visuali): {removed_count}")

    # Leggi le dimensioni dal manifest esistente per non doverle ricalcolare
    txt = MANIFEST.read_text(encoding="utf-8")
    dim_map = {}
    for m in re.finditer(r'"src":\s*"([^"]+)"[^{}]*?"w":\s*(\d+)[^{}]*?"h":\s*(\d+)', txt):
        rel = m.group(1)
        name = os.path.basename(rel)
        dim_map[name] = (int(m.group(2)), int(m.group(3)))

    out = "/* Auto-generated by scripts/dedup-foto.py (dedup percettivo). */\n"
    out += "window.BAZZANA_FOTO = [\n"
    lines = []
    for f in keep:
        w, h = dim_map.get(f, (1400, 933))
        rel = f"assets/img/bazzana/{f}"
        lines.append(f'{{"src":"{rel}","w":{w},"h":{h}}}')
    out += ",\n".join(lines)
    out += "\n];\n"

    MANIFEST.write_text(out, encoding="utf-8")
    print(f"Scritto manifest: {MANIFEST}")


if __name__ == "__main__":
    main()
