#!/usr/bin/env python3
"""Importa TUTTE le foto Bazzana (~244) per la pagina gallery.
- Resize: max 1400px lato lungo (peso ridotto rispetto alle scena-XX 1800px)
- EXIF orientation
- JPEG q=80 progressive
- Output: assets/img/bazzana/foto-001.jpg → foto-244.jpg
- Genera anche manifest JSON con dimensioni per il layout masonry
"""
import os
import json
from pathlib import Path
from PIL import Image, ImageOps

SOURCE = Path("C:/Users/ilbug/Desktop/scuola/gestione/foto bazzana")
DEST = Path(os.path.dirname(__file__)).parent / "assets" / "img" / "bazzana"
DEST.mkdir(parents=True, exist_ok=True)
MANIFEST = Path(os.path.dirname(__file__)).parent / "js" / "foto-manifest.js"

files = sorted([f for f in SOURCE.iterdir() if f.suffix.lower() in {".jpg", ".jpeg"}])
print(f"Totale source: {len(files)}")

MAX_SIDE = 1400
QUALITY = 80

manifest = []
for i, src in enumerate(files, start=1):
    out_name = f"foto-{i:03d}.jpg"
    out_path = DEST / out_name
    # Salta se già esiste (idempotente)
    if out_path.exists() and out_path.stat().st_size > 50000:
        try:
            img = Image.open(out_path)
            manifest.append({"src": f"assets/img/bazzana/{out_name}", "w": img.size[0], "h": img.size[1]})
            continue
        except Exception:
            pass
    try:
        img = Image.open(src)
        img = ImageOps.exif_transpose(img)
        w, h = img.size
        if max(w, h) > MAX_SIDE:
            if w >= h:
                new_w = MAX_SIDE
                new_h = int(h * MAX_SIDE / w)
            else:
                new_h = MAX_SIDE
                new_w = int(w * MAX_SIDE / h)
            img = img.resize((new_w, new_h), Image.LANCZOS)
        if img.mode != "RGB":
            img = img.convert("RGB")
        img.save(out_path, "JPEG", quality=QUALITY, optimize=True, progressive=True)
        manifest.append({"src": f"assets/img/bazzana/{out_name}", "w": img.size[0], "h": img.size[1]})
        if i % 20 == 0:
            print(f"  ... {i}/{len(files)}")
    except Exception as e:
        print(f"  ERROR {src.name}: {e}")

# Manifest JS file
with open(MANIFEST, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by import-all-photos.py */\n")
    f.write("window.BAZZANA_FOTO = ")
    json.dump(manifest, f, ensure_ascii=False, indent=0)
    f.write(";\n")

print(f"\nDone. {len(manifest)} foto in {DEST}")
print(f"Manifest: {MANIFEST}")
